# Sentrix Backend Configuration
# Configuración del Backend de Sentrix

service_name: "sentrix-backend"
version: "1.0.0"
debug: true

# Database configuration
database:
  url: "postgresql://localhost:5432/sentrix"
  max_connections: 10
  timeout_seconds: 30
  retry_attempts: 3
  enable_logging: false

# YOLO Service integration
yolo_service:
  url: "http://localhost:8001"
  timeout_seconds: 60.0
  max_retries: 3
  confidence_threshold: 0.5
  batch_size: 10

# CORS configuration
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
  allow_credentials: true
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"

# Security configuration
security:
  jwt_secret_key: "development-secret-key-change-in-production"
  jwt_expiration_hours: 24
  max_file_size_mb: 50
  allowed_file_types:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".bmp"
    - ".heic"
  rate_limit_per_minute: 60

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  console_logging: true
  max_file_size_mb: 10
  backup_count: 5

# Backend-specific settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1

analysis:
  default_confidence_threshold: 0.5
  max_batch_size: 50
  enable_gps_extraction: true

storage:
  upload_directory: "uploads"
  max_upload_size_mb: 50