path: C:\Users\manolo\Documents\Tesis\yolo-service\data
train: images/train
val: images/val
test: images/test

names:
  0: Basura
  1: Calles mal hechas
  2: Charcos/Cumulo de agua
  3: Huecos

task: segment
nc: 4